#pragma config(Sensor, in1,    leftFrontLight, sensorLineFollower)
#pragma config(Sensor, in2,    leftMidLight,   sensorLineFollower)
#pragma config(Sensor, in3,    leftBackLight,  sensorLineFollower)
#pragma config(Sensor, in4,    rightFrontLight, sensorLineFollower)
#pragma config(Sensor, in5,    rightMidLight,  sensorLineFollower)
#pragma config(Sensor, in6,    rightBackLight, sensorLineFollower)
#pragma config(Sensor, in7,    potOne,         sensorPotentiometer)
#pragma config(Sensor, in8,    potTwo,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftFingerSwitch, sensorDigitalIn)
#pragma config(Sensor, dgtl4,  rightFingerSwitch, sensorDigitalIn)
#pragma config(Sensor, dgtl5,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           fingerY,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftLiftY,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftY,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "FingerBot.c"
#include "autonomous.c"

void pre_auton()
{
        bStopTasksBetweenModes = true;

        while(!nLCDButtons){
                wait1Msec(5);
                clearLCDLine(0);
                clearLCDLine(1);
                displayLCDString(0,0,"Selecting Program: ");
                displayLCDNumber(0,0,programSelected(8));
        }
        autonSelection = programSelected(8);
}

task autonomous()
{
        //Step One: Rotate with the preload and grab cube
        //Step Two: Raise and knock off middle stars
        //Step Three: Drop everything than move straight back
        //Step Four: Strafe left to center on left wall section
        //Step Five: Drive forward and knock off stars with claw open
        startTask(lightMonitor);
        startTask(fingerMonitor);

        switch(autonSelection){
                case 0:
                        autonZero();
                        break;
                case 1:
                        autonOne();
                        break;
                case 2:
                        autonTwo();
                        break;
                case 3:
                        autonThree();
                        break;
                case 4:
                        autonFour();
                        break;
                default:
                        clearLCDLine(0);
                        clearLCDLine(1);
                        displayLCDString(0,0,"Invalid");
                        displayLCDString(1,0,"Selection");
                        break;
        }
}

task usercontrol()
{
        startTask(fingerMonitor);
        startTask(lightMonitor);
        while (true)
        {
                if(vexRT[Btn6U] == 1){
                        raiseLift(0);
                }
                if(vexRT[Btn6D] == 1){
                        lowerLift(0);
                }
                if(vexRT[Btn6U]==0 && vexRT[Btn6D]==0){
                        stopLift();
                }

                if(vexRT[Btn5D] == 1){
                        closeClaw(0);
                }else if(vexRT[Btn5U] == 1){
                        openClaw();
                }

                if(vexRT[Btn7R] == 1){
                        strafeRight(0);
                }
                if(vexRT[Btn7L] == 1){
                        strafeLeft(0);
                }
                if(vexRT[Btn7R] == 0 && vexRT[Btn7L] == 0){
                        analogDrive();
                }
        }
}
