#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    leftFrontLight, sensorNone)
#pragma config(Sensor, in2,    leftMidLight,   sensorLineFollower)
#pragma config(Sensor, in3,    leftBackLight,  sensorLineFollower)
#pragma config(Sensor, in4,    rightFrontLight, sensorLineFollower)
#pragma config(Sensor, in5,    rightMidLight,  sensorLineFollower)
#pragma config(Sensor, in6,    rightBackLight, sensorLineFollower)
#pragma config(Sensor, in7,    potOne,         sensorPotentiometer)
#pragma config(Sensor, in8,    potTwo,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  liftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftFingerSwitch, sensorDigitalIn)
#pragma config(Sensor, dgtl4,  rightFingerSwitch, sensorDigitalIn)
#pragma config(Sensor, dgtl5,  rightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftQuad,       sensorQuadEncoder)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           fingerY,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftLiftY,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftY,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "gyroLib2.h"

void pre_auton()
{
	GyroInit();
  bStopTasksBetweenModes = true;
}

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
	int scale = 102;
  while (true)
  {
  	writeDebugStreamLine("Gyro Lib Angle: %f\n", GyroAngleDegGet());
  	writeDebugStreamLine("Gyro Raw Angle: %f\n", SensorValue[in1]);
  	wait1Msec(50);
  	clearDebugStream();

  	if(vexRT[Btn8U]){
  		GyroReinit();
  	}

  	//writeDebugStreamLine("GYRO ANGLE: %f\nGYRO SCALE: %d", SensorValue(in1), scale);
  	//wait1Msec(5);
  	//clearDebugStream();
  	//if(vexRT[Btn8U]){
  	//	SensorType[in1] = sensorNone;
  	//	SensorType[in1] = sensorGyro;
  	//	SensorFullCount[in1] = 3600;
  	//	SensorScale[in1] = scale;
  	//	writeDebugStream("Reinitializing Gyro.... Wait 1 second...\n");
  	//	wait1Msec(1000);
  	//}

  	//if(vexRT[Btn7U]){
  	//		scale += 1;
  	//		wait1Msec(250);
  	//}
  	//if(vexRT[Btn7D]){
  	//		scale -= 1;
  	//		wait1Msec(250);
  	//}
  }
}
